server:
  port: 8080
logging:
#  config: classpath:logback.xml
  path: D:\log
#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studybootdo
    username: root
    password: bobo
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  typeAliasesPackage: cn.wzl.studybootdo.model       #实体bean包
  mapperLocations: classpath:cn/wzl/studybootdo/dao/**/mapper/*Mapper.xml   #映射文件存放地址

